name: Verification du Projet Book
# Quand doit-il travailler ?
on: [push] # Dès que tu envoies du code sur Github
# Qu'est-ce qu'il doit faire ?
jobs:
  verification-basique:
    runs-on: ubuntu-latest # Il utilise un ordinateur sous Linux
    steps:
      - name: Recuperer le code
        uses: actions/checkout@v4 # Il fait un "copy-paste" du code
      - name: Installer PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5' # Il installe la même version que toi
      - name: Verifier l'installation
        run: composer install --no-scripts # Il vérifie que tout fonctionne